server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sourceidea?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ily520wan
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  redis:
    host: 47.107.133.24
    port: 6379
    database: 0

mybatis:
  type-handlers-package: cn.bb.sourceideamanage.entity
  mapper-locations: classpath:mappler/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #二级缓存
jedis:
  port: 47.107.133.24

# 日志打印sql语句cn.bb.sourceideamanage.dao
logging:
  level:
    cn:
      bb:
        sourceideamanage:
          dao: debug
# 控制台信息
debug: true

# 缓存失效时间 秒
cache:
  timeOut: 600